### ISSUE TITLE
后台我可以自己搭建吗？

### ISSUE THREAD

**Issue by hanjinfeng0309** [ArchKS/zenlog#1]
我在B站上看到的项目，前端很好看，我想只用前端部分，后台我自己用SpringBoot搭一个

**Comment by ArchKS** [comment]
可以的，不过我没写详细的api文档，你可以在zenlog/src/api/index.js中查看编写的API接口

hanjinfeng0309 ***@***.***> 于2021年5月16日周日 上午11:52写道：

**Comment by hanjinfeng0309** [comment]
数据库就`articles`一张表吗？
